import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LitMatch",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="PT-BR">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link
          rel="stylesheet"
          href={inter.href}
          crossOrigin="anonymous"
        /> 
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
